# Generated by Django 4.2.4 on 2023-08-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('name',), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('payment_date',), 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
